import gradio as gr
import threading
import os
import sys
from pathlib import Path

# ── Attempt to import the crew ──────────────────────────────────────────────
try:
    from crew import EngineeringCrew          # adjust if your class is named differently
    CREW_AVAILABLE = True
except ImportError:
    CREW_AVAILABLE = False


# ── Output directory ─────────────────────────────────────────────────────────
OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)


# ── Core runner ──────────────────────────────────────────────────────────────
def run_crew(requirements: str, module_name: str, class_name: str, progress=gr.Progress()):
    """
    Kick off the CrewAI engineering pipeline and stream results back.
    Yields (status_html, design_md, code_py, frontend_py, test_py, files_list)
    """
    if not requirements.strip():
        yield _status(" Please enter requirements before running.", "warning"), \
              "", "", "", "", []
        return

    if not module_name.strip():
        yield _status(" Please enter a module name.", "warning"), \
              "", "", "", "", []
        return

    if not class_name.strip():
        yield _status("Please enter a class name.", "warning"), \
              "", "", "", "", []
        return

    # Sanitise module name
    module_name = module_name.strip().replace(" ", "_")
    if not module_name.endswith(".py"):
        module_name_file = module_name + ".py"
    else:
        module_name_file = module_name
        module_name = module_name[:-3]

    yield _status("🚀 Starting engineering crew…", "running"), "", "", "", "", []

    inputs = {
        "requirements": requirements.strip(),
        "module_name":  module_name_file,
        "class_name":   class_name.strip(),
    }

    if not CREW_AVAILABLE:
        # ── Demo / dry-run mode when crew isn't importable ────────────────
        yield _status("ℹRunning in DEMO mode (crew not found). Showing placeholder output.", "info"), \
              _demo_design(inputs), \
              _demo_code(inputs), \
              _demo_frontend(inputs), \
              _demo_test(inputs), \
              []
        return

    try:
        result = EngineeringCrew().crew().kickoff(inputs=inputs)

        design_path   = OUTPUT_DIR / f"{module_name}_design.md"
        code_path     = OUTPUT_DIR / module_name_file
        frontend_path = OUTPUT_DIR / "app.py"
        test_path     = OUTPUT_DIR / f"test_{module_name_file}"

        design_md   = design_path.read_text()   if design_path.exists()   else "*(not generated)*"
        code_py     = code_path.read_text()     if code_path.exists()     else "*(not generated)*"
        frontend_py = frontend_path.read_text() if frontend_path.exists() else "*(not generated)*"
        test_py     = test_path.read_text()     if test_path.exists()     else "*(not generated)*"

        output_files = [str(p) for p in OUTPUT_DIR.iterdir() if p.is_file()]

        yield _status("Crew finished successfully!", "success"), \
              design_md, code_py, frontend_py, test_py, output_files

    except Exception as e:
        yield _status(f" Error: {e}", "error"), "", "", "", "", []


# ── Status HTML helper ────────────────────────────────────────────────────────
def _status(msg: str, kind: str = "info") -> str:
    colours = {
        "running": ("#1e3a5f", "#d0e8ff"),
        "success": ("#1a3d2b", "#d4edda"),
        "warning": ("#4d3800", "#fff3cd"),
        "error":   ("#4d0000", "#f8d7da"),
        "info":    ("#1a3050", "#cce5ff"),
    }
    border, bg = colours.get(kind, colours["info"])
    return (
        f'<div style="padding:10px 16px;border-radius:8px;'
        f'background:{bg};color:{border};font-weight:600;'
        f'font-family:monospace;font-size:14px;">{msg}</div>'
    )


# ── Demo placeholders ─────────────────────────────────────────────────────────
def _demo_design(i):
    return f"""# Design: `{i['class_name']}` in `{i['module_name']}`

## Overview
{i['requirements']}

## Classes & Methods

### `{i['class_name']}`
- `__init__(self)` – initialise state
- `run(self, input: str) -> str` – main entry point
"""

def _demo_code(i):
    return f"""# {i['module_name']} — generated by backend_engineer
class {i['class_name']}:
    def __init__(self):
        pass

    def run(self, input: str) -> str:
        # TODO: implement logic
        return f"Result for: {{input}}"
"""

def _demo_frontend(i):
    return f"""import gradio as gr
from {i['module_name'][:-3]} import {i['class_name']}

obj = {i['class_name']}()

def predict(text):
    return obj.run(text)

gr.Interface(fn=predict, inputs="text", outputs="text").launch()
"""

def _demo_test(i):
    return f"""import unittest
from {i['module_name'][:-3]} import {i['class_name']}

class Test{i['class_name']}(unittest.TestCase):
    def setUp(self):
        self.obj = {i['class_name']}()

    def test_run(self):
        result = self.obj.run("test input")
        self.assertIsInstance(result, str)

if __name__ == "__main__":
    unittest.main()
"""


# ── UI ────────────────────────────────────────────────────────────────────────
THEME = gr.themes.Base(
    primary_hue="blue",
    neutral_hue="slate",
    font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "sans-serif"],
    font_mono=[gr.themes.GoogleFont("JetBrains Mono"), "ui-monospace", "monospace"],
).set(
    body_background_fill="#0f1117",
    body_text_color="#e2e8f0",
    block_background_fill="#1e2330",
    block_border_color="#2d3548",
    block_label_text_color="#94a3b8",
    input_background_fill="#151823",
    input_border_color="#2d3548",
    button_primary_background_fill="#2563eb",
    button_primary_background_fill_hover="#1d4ed8",
    button_primary_text_color="#ffffff",
)

with gr.Blocks(theme=THEME, title="Engineering Crew", css="""
    #header { text-align:center; padding: 28px 0 8px; }
    #header h1 { font-size:2rem; font-weight:700; color:#60a5fa; margin:0; }
    #header p  { color:#64748b; margin:4px 0 0; font-size:.95rem; }
    .run-btn   { font-size:1rem !important; height:48px !important; }
    .tab-label { font-weight:600; }
    footer { display:none !important; }
""") as demo:

    # ── Header ────────────────────────────────────────────────────────────
    gr.HTML("""
      <div id="header">
        <h1>⚙️ Engineering Crew</h1>
        <p>Powered by CrewAI · Design → Code → Frontend → Tests</p>
      </div>
    """)

    # ── Inputs ────────────────────────────────────────────────────────────
    with gr.Row():
        with gr.Column(scale=5):
            requirements = gr.Textbox(
                label="What do you want to build?",
                placeholder='e.g. "make a to-do app"  or  "make a calculator"  or  "make a weather dashboard"',
                lines=3,
            )
        with gr.Column(scale=1, min_width=160):
            module_name = gr.Textbox(
                label="Module name",
                placeholder="e.g. todo_app.py",
                value="",
            )
            class_name = gr.Textbox(
                label="Class name",
                placeholder="e.g. TodoApp",
                value="",
            )
    run_btn = gr.Button(" Build it", variant="primary", elem_classes="run-btn")

    # ── Output tabs ───────────────────────────────────────────────────────
    with gr.Tabs():
        with gr.TabItem("Design", elem_classes="tab-label"):
            design_out = gr.Markdown(value="*Output will appear here after the crew runs.*")

        with gr.TabItem(" Backend code", elem_classes="tab-label"):
            code_out = gr.Code(language="python", label="backend module")

        with gr.TabItem("Frontend (app.py)", elem_classes="tab-label"):
            frontend_out = gr.Code(language="python", label="app.py")

        with gr.TabItem(" Tests", elem_classes="tab-label"):
            test_out = gr.Code(language="python", label="test module")

        with gr.TabItem("Output files", elem_classes="tab-label"):
            files_out = gr.File(label="Download generated files", file_count="multiple")

    # ── Status bar ────────────────────────────────────────────────────────
    status_html = gr.HTML(_status("Ready — describe what you want to build and click Build it.", "info"))

    # ── Wire up ───────────────────────────────────────────────────────────
    run_btn.click(
        fn=run_crew,
        inputs=[requirements, module_name, class_name],
        outputs=[status_html, design_out, code_out, frontend_out, test_out, files_out],
    )

    gr.HTML("""
      <div style="text-align:center;color:#334155;font-size:.8rem;padding:16px 0 4px;">
        Engineering Crew · Engineering Lead · Backend Engineer · Frontend Engineer · Test Engineer
      </div>
    """)


if __name__ == "__main__":
    demo.launch(share=False)
